all:
  children:
    linux:
      children:
        control_node:
          hosts:
            debian12:
              os: linux
              ansible_host: 192.168.56.31
              vagrant_box: debian/bookworm64

        linux_hosts:
          hosts:
            stream10:
              os: linux
              ansible_host: 192.168.56.32
              vagrant_box: centos/stream10

            ubuntu24:
              os: linux
              ansible_host: 192.168.56.33
              vagrant_box: cloud-image/ubuntu-24.04

            fedora42:
              os: linux
              ansible_host: 192.168.56.34
              vagrant_box: cloud-image/fedora-42

    windows:
      children:
        domain_controller:
          hosts:
            dc01:
              os: windows
              ansible_host: 192.168.56.10
              vagrant_box: jborean93/WindowsServer2022

        domain_members:
          hosts:
            win-2019:
              os: windows
              ansible_host: 192.168.56.21
              vagrant_box: jborean93/WindowsServer2019

            win-2022:
              os: windows
              ansible_host: 192.168.56.22
              vagrant_box: jborean93/WindowsServer2022
