all:
  children:
    linux:
      children:
        control_node:
          hosts:
            ansible-con-01:
              os: linux
              ansible_host: 192.168.100.31
              mac: 02:56:c0:a8:64:1f
              vagrant_box: debian/bookworm64
              network_interfaces:
                - name: mgmt
                  network: lab-main
                  ip: 192.168.100.31
                  mac: 02:56:c0:a8:64:1f
                  role: management

        linux_hosts:
          hosts: {}

    windows:
      children:
        domain_controller:
          hosts:
            domain-con-01:
              os: windows
              ansible_host: 192.168.100.10
              mac: 02:56:c0:a8:64:0a
              vagrant_box: jborean93/WindowsServer2022
              network_interfaces:
                - name: mgmt
                  network: lab-main
                  ip: 192.168.100.10
                  mac: 02:56:c0:a8:64:0a
                  role: management

        domain_members:
          children:
            windows_member_hosts:
              hosts: {}
