---
# Usage examples:
#   ansible-playbook playbooks/windows-openssh.yml
#   ansible-playbook playbooks/windows-openssh.yml --limit mssql_windows_ag
#   ansible-playbook playbooks/windows-openssh.yml --limit win-cluster-n01
#
- name: install and configure windows openssh server
  hosts: windows
  gather_facts: false
  become: true
  become_method: ansible.builtin.runas
  become_user: SYSTEM

  roles:
    - role: windows_openssh
