lab_domain_controller_host: "{{ groups['domain_controller'] | first }}"
lab_domain_controller_ip: "{{ hostvars[groups['domain_controller'] | first].ansible_host }}"

lab:
  domain:
    name: lab.local
    netbios_name: LAB
    controller_host: "{{ lab_domain_controller_host }}"
    controller_ip: "{{ lab_domain_controller_ip }}"
    safe_mode_password: VagrantPass1
    admin:
      username: vagrant-admin
      password: VagrantPass1
      upn: vagrant-admin@LAB.LOCAL
  kerberos:
    realm: LAB.LOCAL
    kdc_host: "{{ lab_domain_controller_host }}"
    kdc_ip: "{{ lab_domain_controller_ip }}"
  dns:
    mode: local_forwarder
    upstream_server: "{{ lab_domain_controller_ip }}"
  certificates:
    adcs_enabled: true
    autoenroll_enabled: true
    autoenroll_template: WorkstationCertAutoEnroll
    gpo_name: WorkstationCertificateAutoEnroll
    winrm_listener_cert_mode: adcs_autoenroll
  provider_options:
    cpus: 4
    memory_mb: 4096
    memory_backing: "off"
    sync_folders: []
